services:
  api:
    build: .
    container_name: global-energy-api
    ports:
      - "8000:8000"

    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_NAME: energy_market
      DB_USER: urluser
      DB_PASSWORD: ${DB_PASSWORD}

    networks:
      - distributed-url-shortener_default

networks:
  distributed-url-shortener_default:
    external: true